spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/yanghoon?useUnicode=true&charaterEncoding=utf-8"
    username: "yanghoon"
    password: "yanghoon"